apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nikita-meta-name
  annotations:
    # backstage.io/techdocs-ref: url:https://github.com/org/repo
    backstage.io/techdocs-ref: url:https://github.com/NikitaBaranov-Koho/backstage-test/tree/main
    # Or
    # backstage.io/techdocs-ref: url:https://github.com/org/repo/tree/branchName/subFolder 

spec:
  type: service
  lifecycle: production
  owner: team-nik
